### ISSUE TITLE
Éviter les height: auto; sur les images SVG

### ISSUE THREAD

**Issue by creativejuiz** [raphaelgoetter/KNACSS#101]
Hello,
Récemment dans un projet j'ai souhaité insérer le logo du site web en SVG grâce à la balise `<img>`.
Toutes les images dans Knacss héritent des styles : 
`img {
    width: 100%;
    height: auto;
    border: 0;
    vertical-align: middle;
}`
Mon élément image est bien fourni des attributs `width` et `height`.
La largeur est bien respectée (240px) lorsque l'élément s'affiche à l'écran, mais l'élément propose une hauteur supérieure à celle demandée (150px au lieu de 80px). Je ne sais pas d'où sort ce chiffre. L'image n'est pas pour autant déformée, seule la boîte de l'élément l'est.

Pour corriger le tir avec les ressources en SVG, j'ai viré le `height: auto;` appliqué à toutes les images, et ajouté : 
`img:not([src$=".svg"]) {
    height: auto;
}`

Il faudra checker la compatibilité avec les styles optionnels de Google Maps : 
`:not(.gm-style) img {
    height: auto;
}`

Note importante : mon fichier SVG n'a pas de dimensions dans son code, j'imagine que ça joue ;)

**Comment by raphaelgoetter** [comment]
corrigé dans KNACSS v4 (bientôt)
