### ISSUE TITLE
Simplifier la sortie css pour les .grid-n

### ISSUE THREAD

**Issue by eQRoeil** [raphaelgoetter/KNACSS#111]
Bonjour Raphaël,
à la lecture  de la version css j'ai trouvé qu''il y avait beaucoup de répétition des propriétés flexbox.
Pour chaque version de grid-n il y a

~~~
display: -webkit-box;
display: -webkit-flex;
display: -ms-flexbox;
display: flex;
-webkit-box-orient: horizontal;
-webkit-box-direction: normal;
-webkit-flex-direction: row;
-ms-flex-direction: row;
flex-direction: row;
-webkit-flex-wrap: wrap;
-ms-flex-wrap: wrap;
flex-wrap: wrap;
margin-left: -1em;
~~~

__Dans la cas où__ gzip est utilisé, c'est pas vraiment gênant niveau perf...
En revanche, cela rend la lecture pas très agréable.
__Si des gens lisent encore le css généré__ , il pourrait être préférable de ne pas "sortir" tout ça, en modifiant un peu le mixin.
Avantage : code généré plus light
Inconvénient (de ma proposition rapide) : une classe supplémentaire

Ma proposition : quelle que soit la grille que l'on souhaite utiliser écrire

~~~
<div class="grid grid-2"> ... </div>
~~~
ainsi ```.grid-2``` ``` .grid-3``` etc. n'ont pas besoin de règles, seules subsistent les ```.grid-2 > * ```

J'ai créé un pen à partir du tien avec la modif du mixin en Sass : 

http://codepen.io/anon/pen/emjqLJ

en LESS :  

http://codepen.io/anon/pen/QwBePL

C'est un peu l'esprit BEM (pour le modifieur) sans la syntaxe (je sais que tu ne souhaites pas l'utiliser). 
Je n'ai testé qu'avec le fork de tes 2 codepen, j'ai pu louper un truc ;-)

**Comment by raphaelgoetter** [comment]
Salut Pascal et merci pour ton retour.

J'ai également remarqué que la version CSS était rudement lourde en raison des nombreux préfixes flexbox.

Je crois, pour commencer, que mon compileur est mal configuré et qu'il prend en compte *toutes* les versions des navigateurs, même ceux datant de Mathusalem. Régler Autoprefixer sur "last 2 versions" devrait déjà arranger les choses ;)

Ensuite, j'aime bien ton idée de factorisation, mais par contre le fait d'avoir une double classe me dérange beaucoup : ça casse la simplicité et la mécanique du système.

Du coup, j'ai repris ton pen et j'ai simplement changé ton `.grid` en `[class*="grid-"]` et ça me semble parfait comme ça : http://codepen.io/raphaelgoetter/pen/LEJEKe

Tu confirmes ? :)

**Comment by eQRoeil** [comment]
Je n'y avais pas pensé (habitude des modifieurs...)
On pourrait aller plus loin avec 
~~~
[class*="grid-"] > * {
    flex: 0 0 auto;
    display: block; /* IE fix */
    padding: 1em;
    border-left: @gutter solid transparent;
    background-clip: padding-box !important; /* no background on border */
}
~~~ 
ainsi il ne reste plus que le calcul de largeur (et les règles flexbox quand elles sont nécessaires 
(.flexitem-first)

gutter devient obsolète dans le mixin

**Comment by raphaelgoetter** [comment]
ça tient la route, merci !

**Comment by eQRoeil** [comment]
J'ai les versions Sass et LESS compilées.
As-tu un fichier de test pour vérifier que tout fonctionne avec les grilles ?

Si tu veux voir ce que ça donne, c'est sur mon fork <https://github.com/eQRoeil/KNACSS/blob/master/css/knacss.css> (version css compilée depuis less)

**Comment by raphaelgoetter** [comment]
Je pense que c'est bon, j'ai déjà commité le résultat si tu veux vérifier ;)

**Comment by eQRoeil** [comment]
\o/

**Comment by raphaelgoetter** [comment]
mais tu triches, tu n'as pas activé autoprefixer :D

**Comment by eQRoeil** [comment]
oups... je teste koala pour compiler
