### ISSUE TITLE
Le système de grilles ne fonctionne pas sur Android 4.1.2

### ISSUE THREAD

**Issue by MathieuVanDriessche** [raphaelgoetter/KNACSS#112]
Bonjour,

Quand je consulte la page http://codepen.io/raphaelgoetter/full/zxBMLW?editors=110 sur un navigateur Android 4.1.2, les flex-items ne passent pas à la ligne. De plus, il est possible de scroller horizontalement pour afficher le contenu.

Capture réalisée sur un Sony Xperia P Android 4.1.2
![flexbug](https://cloud.githubusercontent.com/assets/11442299/6619810/137f1b6c-c8cd-11e4-8d59-c6dcc25c34e2.jpg)

**Comment by raphaelgoetter** [comment]
Hello,

Effectivement, après tests de notre côté également, je te confirme que flex-wrap n'est pas supporté par Android <4.4.
Je modifie la compatibilité dans la doc.

**Comment by MathieuVanDriessche** [comment]
Bonjour Raphael,

Désolé. J'espère que ce n'est pas un trop mauvaise nouvelle pour toi.

De mon coté,  les versions d'Android qui posent problème représentent +/- 15% de utilisateurs de l'appli sur laquelle je travaille. Je vais donc essayer de concevoir une grille flexbox qui peut se passer de flex-wrap avec un conteneur pour chaque ligne (comme le .row de bootstrap). Cela sera moins flexible mais quand même un peu plus qu'une grille en float ou inline-block.

**Comment by raphaelgoetter** [comment]
En fait, la version originelle de la grille était basée sur `flex: 1 1 X%` et a été remplacée par `width: X%` parce que cela me posait des problèmes sur IE10+

Peut-être que la solution `flex: 1 1 X%` fonctionne sur Android, auquel cas il faudrait voir à tenter un remix des deux ?

Tu pourrais voir à tester directement sur le codepen ?

**Comment by MathieuVanDriessche** [comment]
Je vais retester mais je pense que sur Android inférieur à 4.4 <code>flex: 0 0 50%</code> ne fonctionnait pas. Je devais utiliser <code>width: 50%</code> également.
Par contre, j'ai jamais testé <code>flex: 1 1 X%</code>. Je suis tomber amoureux de flexbox grâce à toi mais j'en suis encore au stade de la découverte. Je chipote donc encore beaucoup...

Je test dès que possible sur codepen et je reviens vers toi.

**Comment by MathieuVanDriessche** [comment]
Malheureusement, <code>flex: 1 1 X%</code> ne semble pas améliorer la situation.
J'ai tenté de créer une grille compatible avec de plus vieux Android. La première version semble fonctionner et répondre à mes besoins pour le projet en cours. Par contre, ce système est bien moins générique et flexible.
http://codepen.io/mathieuVD/full/RNevKy

Bon we et merci pour tout ;-)
