### ISSUE TITLE
Version de grille compatible IE9 ?

### ISSUE THREAD

**Issue by raphaelgoetter** [raphaelgoetter/KNACSS#114]
"il faudrait un KNACSS compatible IE9+ et un KNACSS-Grid compatible IE10+"

**Comment by raphaelgoetter** [comment]
Done v4.3.0

**Comment by PhilippeVay** [comment]
_Du coup_©, les paragraphes sur la [compatibilité IE](https://github.com/raphaelgoetter/KNACSS#compatibilit%C3%A9) (8, 9, 10+) sont-ils toujours valables ?

**Comment by raphaelgoetter** [comment]
corrigé, merci.
