### ISSUE TITLE
Problème de taille de police sous safari <= 6.1

### ISSUE THREAD

**Issue by wayofspark** [raphaelgoetter/KNACSS#116]
Hello,

Le calcule de la taille de font se vautre royalement sous safari <= 6.1

le fautif est 01-base.scss : 

	/* set base font-size to equiv "10px", which is adapted to rem unit */
	font-size: 62.5%;
	
	/* IE9-IE11 math fixing. See http://bit.ly/1g4X0bX */
	/* thanks to @guardian, @victorbritopro and @eQRoeil */
        font-size: calc(1em * 0.625);

En effet safari ne comprend pas le calc sans préfixe, et ne fallback pas sur la déclaration précédente, cassant toute la déclaration en em.

**Comment by raphaelgoetter** [comment]
Bonjour,

C'est bizarre en effet, tu utilises quel outil pour préfixer tes fichiers Sass ?
