### ISSUE TITLE
Problème de bordure des input au focus sous firefox

### ISSUE THREAD

**Issue by MatthieuQuantin** [raphaelgoetter/KNACSS#118]
Bonjour,

Le fait de mettre la propriété "background-image: none;" au focus des input ajoute une bordure sous firefox.

**Comment by raphaelgoetter** [comment]
Merci.

Je pense que je vais limiter aux input de type="button"

**Comment by MatthieuQuantin** [comment]
submit et reset aussi

**Comment by raphaelgoetter** [comment]
Corrigé dans la dernière version. (= supprimé de base et ajout d'une classe `.unstyled` dédiée aux éléments de formulaires.
