### ISSUE TITLE
Classe "flexbox" et Modernizr

### ISSUE THREAD

**Issue by creativejuiz** [raphaelgoetter/KNACSS#119]
Hello m'sieur !

On utilise Modernizr dans un projet afin de détecter la prise en charge de certaines choses par le navigateur, dont flexbox.
Lorsque le navigateur reconnait flexbox, Modernizr ajoute cette classe à HTML.

Comme Knacss utilise `.flexbox` pour appliquer du flex, on se retrouve avec des styles par défaut en flex sur l'élément HTML.

Tout se passe ici : 
https://github.com/raphaelgoetter/KNACSS/blob/master/less/_02-layout.less

Je ne sais pas s'il faut y remédier en renommant la classe, ou pas...
Bon courage !

**Comment by creativejuiz** [comment]
Un petit `.flexbox:not(html)` peut-être ? :p

**Comment by 7studio** [comment]
Salut @creativejuiz,
AMHA, je ne pense pas qu'un outil tel que KNACSS  (ou autre) devrait tenir compte de ce genre de problématiques :expressionless:

Comme KNACSS n'utilise pas (et ne permet pas l'utilisation) de préfixes :stuck_out_tongue_winking_eye:, il faut y donner la priorité sur l'utilisation des noms.

Pour le cas particulier **Modernizr + KNACSS**, je suggérerais l'utilisation de l'option `className prefix` de Modernizr. Peut être faudrait-il noter ce cas d'utilisation dans la document de KNACSS à la place de créer un cas particulier dans le code.

**Comment by magsout** [comment]
Ou alors, penser à ajouter un prefixe au classe KNACSS pour éviter les collisions avec les autres lib ?

**Comment by Nyalab** [comment]
ou alors ne pas appeler ses classnames `.flexbox`ce qui ne veut rien dire, c'est comme appeler une classe `.float` ou `.align`, c'est un type de propriété pas une valeur :speak_no_evil:

**Comment by raphaelgoetter** [comment]
L'idée de `.flexbox:not(html)` me semble plutôt pas mal.

@Nyalab 
> ou alors ne pas appeler ses classnames .flexboxce qui ne veut rien dire

C'est un peu plus compliqué que ça (et de toute façon on utilise *déjà* des classes utilitaires dans KNACSS, telles que `w20`ou `mts` etc. donc la question n'est pas là). Une classe `flexbox` crée un contexte qui permet d'opérer de nombreuses fonctionnalités (centrer, aligner, réordonner). En clair si on devait appeler cette classe par une *fonction* on serait bien embêté, le mieux est d'indiquer clairement qu'il s'agit d'un flex-container.

**Comment by bloodyowl** [comment]
bro do u even scale :neutral_face:

**Comment by Nyalab** [comment]
Comme tu le dis vous utilisez `.w20` qui montre que t'inclus la valeur de la propriété dans ta className. Quoi que tu dises, `flex` ne reste qu'une valeur de `display` dans ce contexte.
Le seul souci que je vois, c'est el conflit entre `display: flex;` et `flex: whatever;` mais pour ça vous avez déjà des shorthands qui le gèrent. Du coup, même si je valide pas, t'aurais : `.flex`, `.flex1`.

**Comment by raphaelgoetter** [comment]
Justement, `flexbox` n'est pas `flex`. il y aurait sans doute beaucoup plus de conflits en nommant cette classe `flex`

**Comment by magsout** [comment]
Je trouve ça étrange d'être obligé d'en arriver à utiliser des classe comme `.flexbox:not(html)`
J'y vois un problème de maintenabilité voir de conception. 

Faut être honnête, et se dire qu'utiliser un seul framework ou une seul lib de nos jours est plutot rare. On en utilise plusieurs un peu partout. 

Le risque de collision est grand, si tu dois t'amuser à utiliser des `not` partout pour palier à ce problème, je trouve plutot cela problèmatique, et pas assez réflechi. Pourquoi ne pas penser justement à éviter ça de façon propre, maintenable et qui dure dans le temps ? 

Par exemple `kc-flexbox` (avec le prefixe que tu veux) même si je rejoins @Nyalab sur le nommage des classe, mais je sais qu'il y a déjà une issue la-desus qui n'a mené à rien.

**Comment by Nyalab** [comment]
![](http://media.giphy.com/media/MUVFUXkCp0DNS/giphy.gif)

**Comment by raphaelgoetter** [comment]
@magsout là aussi c'est vaste : 

- pourquoi Modernizr n'attribue pas de préfixes par défaut, lui ?
- si on préfixe cette classe, il va bien falloir - logiquement - préfixer toutes les classes de KNACSS et j'y suis plutôt opposé

@bloodyowl merci pour ton apport constructif :/

**Comment by magsout** [comment]
@raphaelgoetter 

>Pourquoi Modernizr n'attribue pas de préfixes par défaut, lui ?

Totalement, c'est une erreur de leur part. 

>si on préfixe cette classe, il va bien falloir - logiquement - préfixer toutes les classes de KNACSS 

Nous sommes d'accord

>et j'y suis plutôt opposé

bon ... d'accord...

**Comment by creativejuiz** [comment]
@raphaelgoetter : c'est vrai que si quelqu'un décide volontairement de passe HTML en flexbox, il ne pourrait pas :p 
La classe est assez récente, tu peux encore la renommer.
`.flexbocss`
`.displayflex`
`.flex-box`
`.flexible-box`
etc.

**Comment by bloodyowl** [comment]
@raphaelgoetter le souci c'est que votre bibliothèque n'est utilisable par personne qui:
- souhaite avoir l'assurance d'un risque de collisions réduit au minimum
  - avec le third-party
  - au sein de sa propre codebase
- souhaite une spécificité des sélecteurs équivalente pour le code vendor qu'il souhaite
  potentiellement override.

**Comment by MoOx** [comment]
2015 et des classes names comme ça, aussi vague. Avec tous les articles qu'on peut lire sur les effetcs de bord de ce genre de pratique...
Je pense que je préfère encore utiliser Bootstrap.
Nan je déconne je préfère tout coder mon CSS namespacé. :)

**Comment by raphaelgoetter** [comment]
Nouvelle version, nommages plus consistants : 

```css
[class*="flex-container"] {
	display : flex;
	flex-wrap: wrap;
}

.flex-container-h {
	flex-direction: row;
}

.flex-container-v {
	flex-direction: column;
}

.flex-item-fluid {
	flex: 1;
}

.flex-item-first {
	order : -1;
}

.flex-item-medium {
	order : 0;
}

.flex-item-last {
	order : 1;
}

.flex-item-center {
	margin: auto;
}
```

**Comment by creativejuiz** [comment]
:+1:
