### ISSUE TITLE
Passer toutes les grilles et gouttières en Flexbox

### ISSUE THREAD

**Issue by raphaelgoetter** [raphaelgoetter/KNACSS#12]
voilà voilà voilà :)

**Comment by raphaelgoetter** [comment]
@nhoizey Cet article se base sur l'ancienne version de Flexbox effectivement bien moins performante que les versions récentes.

Paul Irish confirme que c'est beaucoup mieux depuis (et son test a déjà presque 2 ans) : https://css-tricks.com/does-flexbox-have-a-performance-problem/#comment-490956

**Comment by nhoizey** [comment]
Euh… non, mon lien pointait vers un article de Jake Archibald et non Paul Irish, et utilisait à priori bien la dernière version de la syntaxe…

**Comment by raphaelgoetter** [comment]
@nhoizey Ah oui j'ai dû confondre deux articles, il n'est en effet pas vraiment question de performances ici mais de séquence de rendu.

Jake a raison. Mais son choix est tout de même assez spécifique : comme il l'explique, ce rendu est provoqué par le fait que le 1er enfant a un flex:1 et que du coup le navigateur lui attribue toute la largeur en attendant d'avoir les infos des autres enfants.

Pour le coup, les grilles flexbox de KNACSS auront des dimensions explicites en pourcentage et non des flex: 1.

Et sinon, Grid Layout ne sera pas si parfait que ça non-plus : http://blog.goetter.fr/2014/10/27/le-point-sur-les-grilles-en-css/ ;)

**Comment by nhoizey** [comment]
Ok, merci pour l'explication de la différence entre le cas de Jake et KNACSS !

Je vais peut-être finir par me mettre à KNACSS… ;-)

Côté Grid, ce sont surtout les templates avec slots nommés qui m'intéressent, surtout pour des interfaces fullscreen sans scroll, des jeux par exemple… ;-)

**Comment by raphaelgoetter** [comment]
> Côté Grid, ce sont surtout les templates avec slots nommés qui m'intéressent, surtout pour des interfaces fullscreen sans scroll, des jeux par exemple… ;-)

Ce sera un vrai bonheur en effet ! :)
