### ISSUE TITLE
print

### ISSUE THREAD

**Issue by david-deplagne** [raphaelgoetter/KNACSS#121]
Bonjour,
quelle utilité d'avoir à la section print :

`h1, .h1-like {page-break-before: always}`

car on se retrouve avec une page vide en première page imprimée ne contenant que quelques infos propres au navigateur (titre du site en petit dans l'entête, date dans le pied... du moins sur Firefox), donc page plutôt gaspillée.

**Comment by raphaelgoetter** [comment]
C'est vrai que c'est pas idiot comme remarque. Je vais passer cette règle en commentaire, merci.
