### ISSUE TITLE
Classe "fr" et SPIP

### ISSUE THREAD

**Issue by YellowMart** [raphaelgoetter/KNACSS#122]
Hello,

Le passage de v3 à la v4 apporte les classes "fl" et "fr", or SPIP ajoutant l'abréviation de la langue dans les classe de la balise <html> (ex: fr pour francais), ça peut poser des problèmes.

**Comment by raphaelgoetter** [comment]
Le fait que SPIP impose une classe aussi générique que `.fr` sur les éléments me paraît aberrant.

Je vais proposer un "patch" spécifique aux utilisateurs de SPIP, demandant de modifier les fichiers CSS de KNACSS et de remplacer les classes `.fr` et `.fl` par `:not(html) .fr` et `:not(html) .fl` :/

**Comment by YellowMart** [comment]
Ca fait quelques temps que je réfléchis à forker SPIP pour remplacer les styles par défaut de SPIP par Knacss. Il va falloir s'y mettre :)

**Comment by tetue** [comment]
@YellowMart : pas besoin de forker SPIP, fais plutôt un plugin KNACSS pour SPIP, ce serait super !

@raphaelgoetter : le code ISO de la langue de chaque page est effectivement utilisé comme class parente sur l'élément html dans les squelettes par défaut. Je ne sais plus pourquoi on n'utilise pas plutôt le pseudo-élément…

**Comment by YellowMart** [comment]
@tetue : Bonne idée, je m'en occupe ;)

**Comment by raphaelgoetter** [comment]
Cool ! :)

**Comment by MoOx** [comment]
> Le fait que SPIP impose une classe aussi générique que .fr sur les éléments me paraît aberrant.

C'est un peu tout aussi abérrant de voir cette même classe dans une bibliothèque.

**Comment by raphaelgoetter** [comment]
> C'est un peu tout aussi abérrant de voir cette même classe dans une bibliothèque.

C'est pas faux
