### ISSUE TITLE
Erreur compilation version sass - "&" sur _05-forms.scss

### ISSUE THREAD

**Issue by cladjidane** [raphaelgoetter/KNACSS#124]
Il semble y avoir des "&" en trop sur le fichier sass/_05-forms.scss ligne 91 à 93.

Erreur de compilation : 
error sass/style.scss (Line 90 of sass/_05-forms.scss: Invalid CSS after "button": expected "{", was "&,"
"&" may only be used at the beginning of a compound selector.)

**Comment by raphaelgoetter** [comment]
Corrigé dans la dernière version
