### ISSUE TITLE
Quelques doublons

### ISSUE THREAD

**Issue by david-deplagne** [raphaelgoetter/KNACSS#125]
Bonjour Raphaël,

voici quelques doublons et contradictions à vérifier (version V4.1.6 du 2015-04-17)

-----

Lignes 1099 et 1102
Peuvent être regroupées puisque même couleur

`::-webkit-input-placeholder {     
  color: #777;     
}`
`input:-moz-placeholder,     
textarea:-moz-placeholder {     
color: #777;  
}`

-----

Lignes 124 et 1824 -> mark
Déclaré 2 fois :  "background: #ff0"

-----

Ligne 137 et ligne 1828 -> sub, sup

"position: relative " déclarée en double
"vertical-align" différents
`sub,
sup {
  font-size: 75%;
  line-height: 0;
  position: relative;
  vertical-align: baseline;
}`
`sup,
sub {
  vertical-align: 0;
  position: relative;
}`

-----

Lignes 137 et 497 -> sub, sup 
"font-size" différents

`sub,
sup {
  font-size: 75%;
  line-height: 0;
  position: relative;
  vertical-align: baseline;
}`
`small,
sub,
sup {
  font-size: smaller;
}`

-----

Lignes 131 et 497 -> small
"font-size" différents

`small {
  font-size: 80%;
}`
`small,
sub,
sup {
  font-size: smaller;
}`

**Comment by raphaelgoetter** [comment]
Bonjour et merci pour tes retours. Je vais les étudier en détail.

Quelques remarques à chaud : 

> Lignes 1099 et 1102 Peuvent être regroupées puisque même couleur

En fait non : un navigateur qui ne reconnaît pas une partie d'un sélecteur est censé ne rien prendre en compte. Il n'est donc pas possible de regrouper des préfixes différents.

Pour le reste les doublons s'expliquent par l'ajout récent de Normalize.css merci de les avoir signalés.

**Comment by 7studio** [comment]
Salut David,

Les lignes 1099 et 1102 ne peuvent pas être regroupées car le sélecteur ne serait plus interprété et le bloc de déclarations serait ignoré. Fx ne connait pas `::-webkit-` et inversement.

Par contre, on pourrait remplacer `:-moz-placeholder` qui n'est plus interprété par les nouveaux Fx par `::-moz-placeholder` :smile:

**Comment by raphaelgoetter** [comment]
corrigé 4.2.2
