### ISSUE TITLE
conflits [class*="grid-"]

### ISSUE THREAD

**Issue by Reeslo** [raphaelgoetter/KNACSS#129]
C'est la seconde fois que j'ai un conflit sur un projet ou j'utilise fullcalendar.js
J'ai du changer le selecteur class* par class^
Il n'y a pas d'impact sur le fonctionnement de knacss puisque les classes des grilles commencent bien par grid-

Je pense que cela rentrerait moins en conflit avec d'autres classes ex fc-day-grid-container de fullcalendar et de changer [class^="grid-"]

**Comment by raphaelgoetter** [comment]
Hello,

Je comprends ta situation, mais c'est justement volontaire de ne pas imposer aux utilisateurs de commencer par "grid-".

Il me semble indispensable qu'une classe telle que "mod grid-3" continue à fonctionner, sinon on aura une issue par jour de gens qui ne comprennent pas pourquoi ça ne marche pas :)

Bref, si KNACSS entre en conflit avec ton autre outil, il faudra effectivement faire des ajustements à la main.

**Comment by bloodyowl** [comment]
mais vous êtes hallucinants c'est pas croyable.

les gars, réveillez-vous deux secondes:

- vous faites une bibliothèque CSS, donc un truc que les utilisateurs ajoutent chez eux, avec
  leur code, et potentiellement du third-party. vous avez donc la responsabilité de blinder votre
  bibliothèque pour réduire au maximum le risque de conflits avec l'endroit où ça va finir.
- avoir des sélecteurs comme `[class*="grid-"]` faut être cinglé ou jamais avoir utilisé sa lib
  dans le monde réel, vous connaissez les risques de conflits, alors qu'est-ce que ça fout encore
  là?
- demander de modifier à la main la lib, c'est hors de question. si vous avez des MaJ, tout ce que
  doit avoir à faire le dev c'est `npm install` et c'est réglé ; en respectant semver y'aura jamais
  de souci.

> c'est justement volontaire de ne pas imposer aux utilisateurs de commencer par "grid-".

wtf

> Il me semble indispensable qu'une classe telle que "mod grid-3" continue à fonctionner

```html
<div class="mod grid-3">
  <div>
    implicite, pas compréhensible au premier coup d'œil, perte de temps,
    spécificité des sélecteurs complexe, risques de conflits élevés
  </div>
</div>

<div class="k-mod k-grid">
  <div class="k-grid-cell k-grid-cell--3">
    explicite, même spécificité sur chaque classe, risques de conflits peu probables
  </div>
</div>

<div class="ku-Module k-Grid"> <!-- ku = knacss-utils -->
  <div class="k-Grid-cell k-Grid-cell--3">
    explicite, même spécificité sur chaque classe, risques de conflits réduits au maximum
  </div>
</div>
```

si juste vous respectiez BEM pour éviter les conflits, préfixiez vos sélecteurs par `k-` ou un truc
du genre pour bien tout namespacer, que vous sépariez en plusieurs composants (normalize, reset,
grid, images, typography …) vous auriez juste jamais ce genre de problèmes débiles pour une
bibliothèque.

**Comment by raphaelgoetter** [comment]
@bloodyowl : ta hargne serait presque vivifiante et ferait presque avancer les choses mais se heurte à 2 points assez gênants : 

1- tu n'utilises pas KNACSS
2- tu ne connais pas KNACSS

> avoir des sélecteurs comme `[class*="grid-"]` faut être cinglé ou jamais avoir utilisé sa lib dans le monde réel,

Oui, faut nous excuser car on est un peu débutants dans le domaine. Par contre, chez Bootstrap, c'est tout à fait cool d'utiliser à plusieurs endroits des sélecteurs `[class*="col-"]`

> préfixiez vos sélecteurs par k- ou un truc du genre pour bien tout namespacer

Ah mais oui bien-sûr, qu'est-ce qu'on est nouilles quand-même ! Préfixons toutes nos classes par `k-` pour entrer en conflit avec d'autres frameworks, comme par exemple [Kendo UI](http://www.telerik.com/kendo-ui) employé (entre autre) par notre plus grand client.
Ou alors choisissons d'autres préfixes débiles comme `l-`  ou `m-`, ... Ah mince c'est déjà proposé par SMACSS. Ou bien alors ... ah ben non c'est déjà pris aussi :(

C'est tellement évident de penser à namespacer que tous ceux qui ne le font pas sont vraiment des nazes. Enfin sauf Bootstrap, Foundation, Skeleton, WebStarterKit, etc.

(tout ça pour dire que sur le fond tu n'as pas tort, mais que si c'était si simple à faire tout le monde le ferait)

> que vous sépariez en plusieurs composants (normalize, reset,
grid, images, typography …) vous auriez juste jamais ce genre de problèmes débiles pour une
bibliothèque.

Merci pour ce joli argument final qui montre bien que tu n'as jamais mis les mains dans KNACSS : c'est exactement comme ça qu'est structuré KNACSS depuis 3 versions.

Bref, pour en revenir au sujet et au problème initial, s'il y a conflit entre deux systèmes de grilles il est parfaitement possible de ne pas importer celle de KNACSS.

**Comment by bloodyowl** [comment]
tu as raison, je n'utilise pas KNACSS, et je n'aime ni son approche ni son absence de méthodologie, principalement pour du third-party. ceci étant, ça ne change absolument rien aux points remontés qui sont génériques et s'appliquent à n'importe quel CSS.

> Par contre, chez Bootstrap, c'est tout à fait cool d'utiliser à plusieurs endroits des sélecteurs [class*="col-"]

bootstrap a un approche tout aussi conflict-prone (comme l'a admis son créateur https://medium.com/@fat/mediums-css-is-actually-pretty-fucking-good-b8e2a6c78b06)

> Ou alors choisissons d'autres préfixes débiles comme l- ou m-, ... Ah mince c'est déjà proposé par SMACSS. Ou bien alors ... ah ben non c'est déjà pris aussi :(

c'était un exemple, préfixez par `kna-` et c'est réglé.

> C'est tellement évident de penser à namespacer que tous ceux qui ne le font pas sont vraiment des nazes. Enfin sauf Bootstrap, Foundation, Skeleton, WebStarterKit, etc.

nan nan, pas sauf chez eux. c'est aussi naze là bas. populaire n'est pas synonyme de bonne pratique.

> Merci pour ce joli argument final qui montre bien que tu n'as jamais mis les mains dans KNACSS : c'est exactement comme ça qu'est structuré KNACSS depuis 3 versions.

n'utilisant ni less, ni sass, j'ai pas trouvé la séparation adéquate pour ne pas importer votre système de grilles https://github.com/raphaelgoetter/KNACSS/tree/master/css

**Comment by raphaelgoetter** [comment]
Disons qu'en effet, si tu n'utilises ni KNACSS, ni LESS, ni Sass, ni Bootstrap, ni aucun framework (parce que tout est naze), je crois qu'aucun argument que je pourrais apporter te conviendra.

Bonne journée ;)

**Comment by bloodyowl** [comment]
si, j'utilise [cssnext](https://github.com/cssnext/cssnext) avec [cssrecipes](https://github.com/cssrecipes) :)

**Comment by raphaelgoetter** [comment]
Amen

**Comment by magsout** [comment]
@raphaelgoetter je t'invite vraiment à lire les discussions qui émanent de ce tweet https://twitter.com/necolas/status/591267978534002689
C'est très instructif, peut-être que eux (dev chez Twitter, facebok etc...) auront plus de légitimité à tes yeux que nous pauvres développeurs qui n'aimons rien et n'utilisons rien.

**Comment by raphaelgoetter** [comment]
> auront plus de légitimité à tes yeux que nous pauvres développeurs qui n'aimons rien et n'utilisons rien.

1- ce n'est pas moi qui vient de débarquer en disant que ce qu'on fait ici est de la merde
2- je viens juste d'apprendre que des outils tels que Boostrap, Foundation (légitimité ?) sont aussi de la merde, laisse-moi me remettre de mes émotions s'il te plaît ;)

**Comment by magsout** [comment]
>1- ce n'est pas moi qui vient de débarquer en disant que ce qu'on fait ici est de la merde

L"art et la maniere de s'exprimer ne sont peut-etre pas adapatées, il est vrai.

>2- je viens juste d'apprendre que des outils tels que Boostrap, Foundation (légitimité ?) sont aussi de la merde, laisse-moi me remettre de mes émotions s'il te plaît ;)

C'est une question de point de vue.  N'es-tu pas d'accord que coder un site sur une base de bootstrap et l'adapter reléve quand même de la migraine ?

Comme l'a dit @bloodyowl même l'auteur dit que Boostrap s'est cool mais pas pour utiliser en production. Boostrap n'est même pas utilisé sur Github alors que l'auteury travaille. De plus il est juste question de convention et de modularité (inexistant pour le coup)  qui sont critiqués 

Pour les namespaces et autre, tu peux constater que tu commences à avoir quelques issues sur ce sujet https://github.com/raphaelgoetter/KNACSS/issues/122 && https://github.com/raphaelgoetter/KNACSS/issues/119

**Comment by zoontek** [comment]
@raphaelgoetter Une solution peut-être de préfixer à l'aide d'une variable en SASS.
ça ne mange pas de pain, c'est  une adaptation simple à faire du code, et avec !default ça évite d'avir à modifier à la main la lib (une aberration, surtout si on utilise bower / npm)

```scss
$namespace: '';

// Ici, l'import de knaccss
import 'knacss';
// ou tu déclares un $namespace: 'kna-' !default - ou $namespace: '' !default si tu veux laisser ça vide
```

**Comment by raphaelgoetter** [comment]
@zoontek : c'est une super idée ça, je garde de côté, merci.

**Comment by Reeslo** [comment]
:+1:  pour @zoontek  :)
