### ISSUE TITLE
Bug : .grid-3 et IE11

### ISSUE THREAD

**Issue by G3ronim0** [raphaelgoetter/KNACSS#133]
Bonjour, je viens de m'apercevoir que la classe .grid-3, est buggué sur IE11 : [voir un example]( http://codepen.io/G3ronim0/full/aOBvmR/). Je n'ai pas d'IE10 sous la main pour tester.

Je me suis aperçu que la propriété :   width: calc(100% * 1 / 3 - 1em); doit être interprétée diiférement que sur les autres navigateurs. En augmentant la goutière à 1.01em par exemple cela semble fixer le problème.

Mais je ne vois comment proposer un fix propre sur les mixins LESS ou SASS.

**Comment by raphaelgoetter** [comment]
Si j'ai bien compris, tous les navigateurs fonctionnent de la même manière aujourd'hui pour les arrondis, mais IE ne tient compte que des 2 premières décimales : http://cruft.io/posts/percentage-calculations-in-ie/

D'où le bug.

Par contre je n'ai pas encore trouvé comment fixer proprement ce comportement sans avoir à faire du traitement spécifique à IE :/

**Comment by PhilippeVay** [comment]
Je proposerais bien un hack [IE10-11](http://browserhacks.com/#hack-f1070533535a12744a0381a75087a915)

    :-ms-input-placeholder,
    :root .grid-3 {
	/* */
}

qui est bon comme du `.grid-3:nth-of-type(1n) { property: value\9; }` ou du `_:-ms-fullscreen, :root .grid-3 { /* */ }` mais je crains d'être pris au sérieux...

**Comment by G3ronim0** [comment]
Ok je vais traiter sur spécifiquement sur IE.

@raphaelgoetter bien vu le retrait de l'alignement par défault le space-between n'était pas naturel quand il manquait un élément sur la ligne.

**Comment by 7studio** [comment]
Bonjour messieurs :bowtie:

IE  semble accepter d'arrondir le résultat à une décimale inférieure en retirerant `.01px` du calcul :unamused:

Cela n'est pas <del>très</del> propre mais ça a le mérite de corriger le problème de @G3ronim0 sans compromettre le bon fonctionnement des grilles dans les autres navigateurs.

Exemple ici : http://codepen.io/7studio/full/yNVqKp/

**Comment by G3ronim0** [comment]
@7studio bonjour, c'est ce que j'ai mis en place actuellement. Cela n'a pas d'effet de bord sur le rendu des autres navigateurs testés. C'est pas propre mais mieux qu'un hack ;-)

**Comment by raphaelgoetter** [comment]
corrigé 4.2.2
