### ISSUE TITLE
problème de grilles avec knacss et safari

### ISSUE THREAD

**Issue by oliloweb** [raphaelgoetter/KNACSS#134]
Bonjour,
j'utilise knacss avec un systeme de grilles, mais avec Safari les grilles s'affichent toutes les unes en dessous des autres quel que soit le type d'écran. 
Je n'ai pas ce problème avec les autres navigateurs même IE affiche le site correctement...
Le code CSS pour les grilles est un peu complexe pour moi, que puis faire pour remédier à ça?

J'utilise la version 5.1.7 de safari et j'ai windows seven.
Il s'agit d'un site pour un ami qui possède un Mac et c'est lui qui m'a signalé le problème, donc sur Mac... Je n'avais pas vérifié avant  Smiley decu 
J'ai remarqué que le même problème se pose en mode colonnes...
Et aussi avec Opéra....

Merci pour vos réponses

**Comment by raphaelgoetter** [comment]
Bonjour.

Pour ce qui est de Safari Windows :
- c'est un navigateur extrêmement peu employé sur Windows
- c'est un navigateur qui n'est plus tenu à jour depuis des années

Par contre, c'est plus étonnant sur Mac. Serait-il possible que ton ami soit sur une très ancienne version de Safari Mac ?

- Si oui, tu peux éventuellement lui proposer de la mettre à jour.
- Si non, c'est problématique car les grilles de KNACSS n'ont jamais été supportées par les très vieilles versions de Mac. Il faudrait éventuellement créer ta propre version de grilles, par exemple [en bon vieux "float"](http://blog.goetter.fr/2014/10/27/le-point-sur-les-grilles-en-css/).

Bonne journée

**Comment by oliloweb** [comment]
Bonjour Raphael,

C'est effectivement une vielle version: 4.1.3 !!!
C'est aussi un vieux MacBook, je lui est proposé de passer sur Chrome.
J'hésite entre laisser comme ça et ne rien toucher ou passer au "float" ce qui me fait reprendre tous les media-queries que je ne maîtrise pas parfaitement...

Merci pour tes réponses en tous cas, c'est vraiment sympa!
Bonne journée aussi.

**Comment by PhilippeVay** [comment]
Les versions 7 et 8 sont considérées comme récentes, la question se pose pour 6 voire 5 mais 4 c'est très vieux oui. Et très peu utilisé d'après http://caniuse.com/usage-table

**Comment by oliloweb** [comment]
Oui, safari pour windows est la version 5.1.7 et ça ne fonctionne pas; je ne sais pas après... 
Par contre le même problème se pose avec Opéra et là j'ai une version récente: 12.17
toutes les grilles s'affichent les unes en dessous des autres...

**Comment by PhilippeVay** [comment]
12.x est la dernière version d'Opera utilisant le [moteur de rendu Presto](http://en.wikipedia.org/wiki/Presto_%28layout_engine%29), qui semble dater de 2 ans et demi. Depuis la version 15 (début 2013), Opera utilise Blink tout comme Chrome.

**Comment by oliloweb** [comment]
Merci pour vos réponses, 
j'ai personnalisé les média-queries et je vais laisser le site tel quel.
Je sais c'est pas top, mais tant pis pour les utilisateurs de vieilles bécanes, de toutes façons ils ont plus de chances d'aller vers une version plus récente, que nous de retourner vers une ancienne...
