### ISSUE TITLE
<select> font-size sur Chrome et Safari avec OSX

### ISSUE THREAD

**Issue by williamvivier** [raphaelgoetter/KNACSS#135]
Juste pour signaler que le "font-size: inherit;" pour la balise select n'est pas pris en compte sur Chrome et Safari sous OSX, pour corriger voici le code à ajouter:

```
select {
	-webkit-appearance: menulist-button;
}
```

Pour plus d'info : 
http://stackoverflow.com/questions/5345897/html-select-font-size

**Comment by raphaelgoetter** [comment]
done 4.2.2
