### ISSUE TITLE
Utiliser !default dans la config en sass

### ISSUE THREAD

**Issue by fgirardey** [raphaelgoetter/KNACSS#137]
Bonjour à tous,

Que pensez vous de l'amélioration suivante : Ajouter `!default` aux variables SASS dans le fichier `_00-config.scss`

Exemple :
```sass
// font sizes
$base-font-size : 14px !default; // if "14px" then 1em = 14px
$line-height    : 1.5 !default; // equiv line-height 1.5
$h1-size        : 3.2rem !default; // equiv "32px"
$h2-size        : 2.8rem !default; // equiv "28px"
$h3-size        : 2.4rem !default; // equiv "24px"
$h4-size        : 2.0rem !default; // equiv "20px"
$h5-size        : 1.8rem !default; // equiv "18px"
$h6-size        : 1.6rem !default; // equiv "16px"
```

Dans mon cas, j'utilise KNACSS avec bower et je compile en faisant un includePaths du dossier Sass de KNACSS. Du coup à l'heure actuelle je ne peux surcharger le fichier `_00-config.scss` l'ajout de `!default` aux variables permettrait de résoudre ce problème.

- Voir [la documentation](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#variable_defaults_)
- Mon pull request #138

**Comment by raphaelgoetter** [comment]
Done in 4.2.2 ;)
