### ISSUE TITLE
supprimer le namespace sur certains mixins classiques

### ISSUE THREAD

**Issue by raphaelgoetter** [raphaelgoetter/KNACSS#139]
Impossible de faire un simple `.toto { .clearfix }` avec ce genre de mixins : 

```
/* blocks that must contain floats */
.@{kna-namespace}clearfix,
.@{kna-namespace}line {
	&::after {
		content: "";
		display: table;
		clear: both;
		border-collapse: collapse;
	}
}
```

Donc je pense supprimer le namespace pour certaines fonctions classiques telles que le clearfix.

Bonne idée ou il y a mieux à faire ?

**Comment by GaetanBt** [comment]
Pas possible en faisant un `.toto { .@{kna-namespace}clearfix }` ?

**Comment by raphaelgoetter** [comment]
@GaetanBt non, malheureusement

**Comment by GaetanBt** [comment]
Ah, crotte...

**Comment by PhilippeVay** [comment]
Il semble que ce soit le même problème qu'[extend](http://lesscss.org/features/#extend-feature-selector-interpolation-with-extend), en tout cas la conséquence est la même.

> Extend is NOT able to match selectors with variables. If selector contains variable, extend will ignore it.

À propos des mixins: [Combining Styles / a more advanced mixin](http://lesscss.org/features/#extend-feature-combining-styles-a-more-advanced-mixin)

> Another use-case is as an alternative for a mixin - because mixins can only be used with simple selectors, (…)

**Comment by PhilippeVay** [comment]
Perso je doublonnerais le code : règles CSS avec **namespace** puis mixin avec paramétre (ce dernier ne fait pas partie des CSS en sortie, c'est du code LESS à usage interne)

    /* blocks that must contain floats */
    .@{kna-namespace}clearfix,
    .@{kna-namespace}line {
        &::after {
            content: "";
            display: table;
            clear: both;
            border-collapse: collapse;
        }
    }
    /* teh mixin() */
    .clearfix() {
        &::after {
            content: "";
            display: table;
            clear: both;
            border-collapse: collapse;
        }
    }

Et peut-être qu'on peut réunir les 2 avec un sélecteur en 3 parties, j'ai jamais testé :

    .@{kna-namespace}clearfix,
    .@{kna-namespace}line,
    .clearfix() {
      /* */
    }
