### ISSUE TITLE
Erreur compilation sass

### ISSUE THREAD

**Issue by stephendltg** [raphaelgoetter/KNACSS#140]
Une erreur de compilation de la version sass de knacss 4.2.3 et 4.3 : fichier  "_10-styling.scss"  - ligne 103.
Erreur d'utilisation de variable @small-value à corriger par $small-value.

En tout cas excellent l'usage de grid pour IE < 10.

**Comment by raphaelgoetter** [comment]
Merci, je devrais tester plus souvent le résultat compilé via Sass :/

(j'en ai profité pour améliorer la version responsive des grilles)

**Comment by magsout** [comment]
@raphaelgoetter tu devrais ajouter un test de compile et un travis ?

**Comment by raphaelgoetter** [comment]
@magsout oui en effet !

**Comment by stephendltg** [comment]
J'adore la nouvelle version responsive des grilles. Je trouve plus souple de définir les règles responsive.
UN ENORME MERCI !!!

**Comment by raphaelgoetter** [comment]
Merci à toi pour ce retour très encourageant :)
