### ISSUE TITLE
Feuille de style print

### ISSUE THREAD

**Issue by raphaelgoetter** [raphaelgoetter/KNACSS#145]
Ne pas imposer de couleur de texte, fond, image. Laisser l'utilisateur faire.

cf. https://twitter.com/Tornoz/status/626073000727703552

**Comment by 7studio** [comment]
:+1:

Je profite de cette issue pour soulever deux autres points :  

1. Souligner les liens a-t-il un intérêt à l'impression ? (ex. : [Le Figaro](http://www.lefigaro.fr/conjoncture/2015/03/30/20002-20150330ARTFIG00074-emploi-impots8230-apres-la-claque-electorale-valls-annonce-deja-des-reformes.php?print=true))
2. Afficher les URLs des liens par défaut est-il toujours une bonne idée ? (ex. : [VisitScotland](http://www.visitscotland.com/blog/edinburgh-lothians/edinburgh-hidden-gems/))

Concernant le point 2, voici une autre [issue](https://github.com/vladocar/Hartija---CSS-Print-Framework/issues/1) (en anglais) qui soulève une autre problématique de cette technique.
