### ISSUE TITLE
NPM version

### ISSUE THREAD

**Issue by WedgeSama** [raphaelgoetter/KNACSS#147]
J'utilise npm pour gérer mes deps et en ajoutant knacss, j'ai remarqué que la dernière version accessible par ce biais est la 4.0.3 qui date de début mars. Serais-ce possible d'avoir les autres versions (et notamment la dernière 4.3.2) ?

En attendant, j'utilise `"knacss": "https://github.com/raphaelgoetter/KNACSS.git",` pour importer knacss mais c'est moins propre.

**Comment by raphaelgoetter** [comment]
Résolu :)
