### ISSUE TITLE
Offset grid

### ISSUE THREAD

**Issue by fgirardey** [raphaelgoetter/KNACSS#157]
Bonjour,

Il semblerait que la solution pour faire [des offsets](https://github.com/raphaelgoetter/KNACSS/blob/master/doc/03-grilles.md#offsets) avec les grid serait d'utiliser les classes `left` ou `right`.

Or dans le cas où l'ont souhaite pousser à droite un flex-item, la classe `right` n'a aucun effet car son sélecteur a moins de poids que celui des grilles qui met déjà un `margin-left: 1em;`

Je n'ai pas vraiment d'idée sur ce qui pourrait convenir comme solution, peut-être créer des classes spéciales pour les offsets justement ? Du style `flex-item-left` `flex-item-right`

J'ai un [petit exemple](http://codepen.io/fgirardey/pen/rOBLJa?editors=110) mais bon voilà, le débat est lancé sur quelle est la meilleure solution.

**Comment by raphaelgoetter** [comment]
Bonjour,

en effet, la question s'est posée il y a quelques temps : https://github.com/raphaelgoetter/KNACSS/pull/148 ;)

**Comment by fgirardey** [comment]
Oups, je n'avais pas pensé à regarder dans les pull requests, du coup bah bonne vacances 😅

**Comment by raphaelgoetter** [comment]
Héhé. Je suis rentré hier, donc je vais débroussailler tout ça aujourd'hui ;)

**Comment by fgirardey** [comment]
Bon courage 😊
