### ISSUE TITLE
Erreur de frappe ?

### ISSUE THREAD

**Issue by Reeslo** [raphaelgoetter/KNACSS#160]
Est-ce que c'est normal le "$= : 
https://github.com/raphaelgoetter/KNACSS/blob/master/sass/_01b-base.scss#L28

**Comment by Reeslo** [comment]
Oops désolé j'ai pas réfléchis avant d'écrire ...

Je vais me cacher :(

**Comment by raphaelgoetter** [comment]
Pas de souci :)

Les spec ici : http://www.w3.org/TR/css3-selectors/#attribute-substrings
