### ISSUE TITLE
Doublon

### ISSUE THREAD

**Issue by david-deplagne** [raphaelgoetter/KNACSS#162]
Bonjour Raphael,

je note un doublon :
  -webkit-text-size-adjust: 100% et -ms-text-size-adjust: 100% 
déclaré 2 fois (ligne 14 et 400)

Ensuite je m'interroge sur :
small {font-size: 80%}
.small {font-size: 0.8em}
est ce que c'est censé donne la même taille de texte ?

Dernièrement, si on a small et .small, table et .table, h1 te .h1-like 
Suivant cette logique, pourquoi pas em et .em (au lieu de .italic) ?

Et comme toujours, merci pour ce formidable outil !

**Comment by raphaelgoetter** [comment]
Hello,

Vu pour le doublon. C'est en partie dû à l'inclusion de Normalize. Je corrige ça dès la prochaine version.

`small {font-size: 80%}` est issu de Normalize. Je n'y touche pas parce qu'il s'agit d'une référence et qu'une mise à jour écraserait de toute façon ce que j'y modifierais, mais je ne suis pas fan de la notation en % alors que `em` est fait pour ça. Pour répondre à ta question : oui c'est censé donner la même taille.

Pour `em` et  `.em` c'est un peu différent puisque `em` ne signifie pas "italique" mais "mise en emphase", donc `.italic` est parfaitement justifié pour une mise en italique.
