### ISSUE TITLE
Une balise script insérée dans un set de colonnes affiche son contenu sur la page

### ISSUE THREAD

**Issue by franck-grenier** [raphaelgoetter/KNACSS#163]
Bonjour,
j'ai placé une balise "script" dans un set de colonnes et le contenu de cette balise (du code Javascript) s'est retrouvé affiché sur la page !

En déplaçant la balise script en dehors du set de colonnes, le code disparaît et l'affichage redevient correct.

**Comment by raphaelgoetter** [comment]
Bonjour,

Qu'appelles-tu un "set de colonnes" ?

Des classes `.col` ? Une grille de type `.grid...` ?

Il me faut plus d'informations.

**Comment by franck-grenier** [comment]
Bonjour,
voici un aperçu du code qui provoque l'anomalie.

```javascript
<div class="unstyled grid-2-small-2-tiny-1">
    <div id="nav-choice-links">.....</div>
    <div class="flex-item-first mbm">.....</div>
    <script type="text/javascript">
        console.log('Cette sortie de console apparaît dans la page => ANOMALIE');
    </script>
</div>
```

L'anomalie est corrigée lorsque je sors la balise `<scrip>t` du `<div class="unstyled grid-2-small-2-tiny-1">`.

> Mais il me faut plus d'informations parce que je ne vois pas trop pourquoi un script pourrait se trouver en plein milieu de la page.

On est bien d'accord sur le placement de cette balise script. Mais ce n'est pas le sujet. Son `display` devrait respecter la règle par défaut des navigateurs et rester à `none`. Donc je pense que KNACSS présente une anomalie sur ce coup là.

**Comment by GaetanBt** [comment]
Ça m'a l'air d'être dû au `display: inline-block` du sélecteur `[class*=grid-]>*` qui surcharge le `display: none` des user agent stylesheet.

**Comment by raphaelgoetter** [comment]
Bonjour Franck,

Il s'agit d'une fonctionnalité souhaitée : en effet, pour assurer une compatibilité IE9 et plus anciens, il a été décidé que les enfants directs d'une grille passaient automatiquement en `display: inline-block` : 

https://github.com/raphaelgoetter/KNACSS/blob/master/less/_03-grids.less#L37

A partir du moment où tu choisis ce système de grille, ce fonctionnement opèrera sinon la grille sera mal affichée sur les anciens navigateurs. C'est un consensus qui est prévu pour s'adapter à l'énorme majorité des cas de figure possible; avoir un élément `<script>` au sein d'éléments de contenu est une anomalie que l'on ne peut pas forcément traiter à l'aide d'un framework généraliste.

Propositions de solutions : 

- modifier la valeur de display à la main
- utiliser un autre mode de positionnement
- continuer à utiliser une grille flexbox mais sans passer par KNACSS
- placer les scripts au bon endroit ;)

Bonne chance !

**Comment by franck-grenier** [comment]
Ok j'ai bien compris.

C'est une particularité qu'il faudrait peut-être mentionner dans la doc car, au premier abord, c'est un peu surprenant et on a du mal à comprendre ce qui se passe.

En tout cas, merci pour le support. Et bonne continuation avec ce framework qui tient toutes ses promesses !
