### ISSUE TITLE
Bouton de formulaire et outline

### ISSUE THREAD

**Issue by jnoesser** [raphaelgoetter/KNACSS#164]
Hello !

Lors d'un test de la navigation au clavier d'un projet intégré avec Knacss, dans le cadre d'un audit accessibilité, j'ai pu constater que le focus n'était pas visible sur les boutons de formulaire.

Après quelques recherches, j'ai trouvé ce qui posait problème dans le fichier _05-forms.less : 
```
.@{kna-namespace}btn:focus,
input[type="button"]:focus,
button:focus {
  outline: 0;
}
```

Est-ce qu'il y a une raison particulière d'appliquer ce `outline: 0` sur l'ensemble des éléments boutons et input ?

Bien entendu chacun·e peut surcharger cette propriété si besoin mais on n'y pense pas forcément, ce qui peut poser des soucis d'accessibilité. ;)

**Comment by fgirardey** [comment]
Complètement d'accord avec @jnoesser, il faudrait enlever cela.

Tu devrais faire un PR :wink:

**Comment by raphaelgoetter** [comment]
Mais carrément !

**Comment by jnoesser** [comment]
Cool merci ! ;)
