### ISSUE TITLE
word-break: break-all sur les liens ?

### ISSUE THREAD

**Issue by raphaelgoetter** [raphaelgoetter/KNACSS#165]
`word-wrap` est tout moche sur les liens (création de hyphens indésirés), du coup, je me tâte à imposer un `word-break` uniquement sur eux

**Comment by PhilippeVay** [comment]
Cette instruction a été ajoutée en lien avec les critères d'accessibilité suivants (référentiel : RGAA 3) : 
* [Pour chaque page Web, en affichage plein écran et avec une taille de police à 200%, chaque bloc de texte reste-t-il lisible sans l'utilisation de la barre de défilement horizontal ?](http://references.modernisation.gouv.fr/referentiel-technique-0#title-critre-1010-aaa-pour-chaque-page-web-en-affichage-plein-cran-et-avec-une-taille-de-police-200-chaque-bloc-de-texte-reste-t-il-lisible-sans-lutilisation-de-la-barre-de-dfilement-horizontal-) (niveau AAA)
* [Dans chaque page Web, le texte reste-t-il lisible lorsque la taille des caractères est augmentée jusqu'à 200%, au moins ?](http://references.modernisation.gouv.fr/referentiel-technique-0#title-critre-104-aa-dans-chaque-page-web-le-texte-reste-t-il-lisible-lorsque-la-taille-des-caractres-est-augmente-jusqu-200-au-moins-) (niveau AA)

**Comment by raphaelgoetter** [comment]
Je ne vois pas où il est question des liens spécifiquement et de word-break (ou équivalent) :/
