### ISSUE TITLE
Grilles de colonnes inégales et RWD

### ISSUE THREAD

**Issue by jnoesser** [raphaelgoetter/KNACSS#167]
Hello Raphaël !

Actuellement il n'est pas possible de rendre facilement responsive les grilles de colonnes inégales (grid-2-1), les mots-clés `-small-*` et `-tiny-*` ne s'appliquent pas dans ce cas là en tout cas.

Pourquoi ne pas écrire : 
```less
[class*="@{kna-namespace}grid-2-1"] {
  .uneven-grid(2,1);
}
```
au lieu de : 
```less
.@{kna-namespace}grid-2-1 {
  .uneven-grid(2,1);
}
```

Ça fonctionne plutôt bien (je n'ai pas rencontré de bug pour l'instant) et ça peut être très pratique quand on en a besoin. ;)

**Comment by jnoesser** [comment]
Oups, finalement j'ai rencontré un petit

**Comment by raphaelgoetter** [comment]
Cool ça m'intéresse, parce que j'ai aussi essayé en croyant que c'était simple :)
