### ISSUE TITLE
Classes d'état

### ISSUE THREAD

**Issue by raphaelgoetter** [raphaelgoetter/KNACSS#169]
Je me tâte à ajouter des classes d'état ("state"), un peu dans la lignée de `.unstyled` déjà existant.

Pour commencer, et pour ajouter un peu de convention de nommage, le principe serait de débuter ces classes par `.is-`, donc plutôt `.is-unstyled`.

Ensuite je pense à ce genre d'ajouts : 

```
.is-disabled,
[disabled] {
  opacity: 0.5;
  pointer-events: none;
  cursor: not-allowed;
  filter: grayscale(1);
}

/* invisible for all */
.is-hidden,
[hidden] {
  display: none;
}

/* hide only visually, but still available for screenreaders */
.is-visually-hidden,
.visually-hidden {
 // comme actuellement
}

.is-unstyled,
.unstyled {
 // comme actuellement
}
```

Des avis, des contre-indications, d'autres idées ?

**Comment by fgirardey** [comment]
Hello,

Je ne suis pas sur que `[aria-hidden="true"]` veuille forcément dire qu'il n'est pas visible par l'utilisateur, c'est un attribut qui sert à faire ignorer un élément aux lecteurs d'écran, cela ne veut pas forcément dire que l'élément doit être masqué.

Exemple avec les thèmes WordPress twenty* : https://github.com/WordPress/twentysixteen/blob/master/inc/template-tags.php#L138-L140

Dans ce cas précis ils masquent les permaliens sur les images car ils font redondance avec les "lire la suite" qui sont affichés plus tard dans les pages archive.
En revanche l'utilisateur a toujours besoin de les voir.

Voilà je ne suis pas du tout expert a11y mais bon c'est mon avis sur le sujet 😅

**Comment by raphaelgoetter** [comment]
Ah oui c'est pas idiot ça, je me renseigne.

**Comment by PhilippeVay** [comment]
`.unstyled` n'est pas un état : c'est un(e absence de) style nan ?

OK pour le préfixe `.is-`: j'ai vu trop de fois des confusions avec par exemple l'utilisation d'une classe `.open` ("est-ce que ça va ouvrir un truc ou bien est-ce déjà ouvert ?") et je recommandais l'utilisation du participe passé mais c'est encore mieux avec ce préfixe.

Pour `[aria-hidden="true"]`, c'est en effet masqué aux lecteurs d'écran et c'est tout, ça ne dit rien de la visibilité à l'écran. Attention aux utilisateurs de lecteurs d'écran mal-voyants : tous ne sont pas non-voyants (aveugles n'ayant comme seule source d'information que ce que leur lecteur d'écran leur transmet), il y en a d'autres qui voient plus ou moins bien leur écran ET se servent d'un lecteur d'écran : s'il y a une grosse différence entre les 2 alors ça va leur poser problème. L'exemple de WordPress où c'est sur un lien, c'est problématique : si on peut tabuler vers ce lien, qu'en plus ça se voit à l'écran mais que le lecteur d'écran ne dit rien errrr il y a de quoi être décontenancé (j'ai pas regardé le contexte de ce lien dans une page mais en tout cas je vois une source de problème/warning)
