### ISSUE TITLE
Classes margin auto

### ISSUE THREAD

**Issue by hiwelo** [raphaelgoetter/KNACSS#170]
Dans l'idée où il existe déjà des classes de margin comme `.man` pour `margin: 0;`, serait-il possible d'avoir des classes pour les marges automatiques, souvent utilisées avec flexbox.

- `.mta` ou `.mtauto` pour `margin-top: auto;`
- `.mba` ou `.mbauto` pour `margin-bottom: auto;`
- `.mla` ou `.mlauto` pour `margin-left: auto;`
- `.mra` ou `.mrauto` pour `margin-right: auto;`
- `.ma` ou `.mauto` pour `margin: auto;`

Merci :smile_cat:

**Comment by raphaelgoetter** [comment]
Super idée :)
