### ISSUE TITLE
Créer une classe .bfc ?

### ISSUE THREAD

**Issue by raphaelgoetter** [raphaelgoetter/KNACSS#176]
Actuellement, la classe passe-partout `.mod` crée un BFC avec le style `overflow: hidden;` 

Si l'intention est clairement de créer un BFC, pourquoi ne pas utiliser une classe `.bfc` ?

**Comment by PhilippeVay** [comment]
Je rajouterais un warning bien explicite dans le genre `.bfc {overflow: hidden; // do NOT expect an element with .bfc class to have ov:h; in a future version of KNACSS it could be display: table or any other declaration creating a BFC`

**Comment by raphaelgoetter** [comment]
mouais, je vois l'idée mais bon...
