### ISSUE TITLE
Knacss 4.4

### ISSUE THREAD

**Issue by stephendltg** [raphaelgoetter/KNACSS#179]
#Normalize:
-> Répétition de la police monospace

code,
kbd,
pre,
samp {
  font-family: monospace, monospace;
  font-size: 1em;
}

-----

#Helper:

Pas de is-visually-hidden

-----

Un grand merci tout cas pour ces nouveaux add-ons.

**Comment by raphaelgoetter** [comment]
Bonsoir.

Pour Normalize, on dirait que c'est volontaire : https://github.com/necolas/normalize.css/issues/480
De toute façon, je préfère laisser Normalize tel quel sinon ça va tout casser dès la mise à jour.

Pour le Helper : bien vu, j'ai un peu oublié :)
