### ISSUE TITLE
Proposition : Redéfinir les classes HTML `.left` et `.right`

### ISSUE THREAD

**Issue by 7studio** [raphaelgoetter/KNACSS#68]
Bonjour Raphael,

Lors de la lecture du [programme de KNACSS v3.0](https://github.com/raphaelgoetter/KNACSS/issues/48) et de ses commentaires, je pensais que les classes HTML `.left` et `.right` seraient <del>tout simplement</del> remplacées. Sauf qu'en parcourant la [partie concernée](https://github.com/raphaelgoetter/KNACSS/blob/master/css/01-base.css#L332-L382), il semble que la rétrocompatibilité (ou une décision personnelle) en a décidé autrement en créant de simples alias.

Je ne vais pas aller contre ce choix <del>discutable</del> mais n'aurait-il pas été intéressant de profiter de l'arrivée de `.start` et `.end` pour demander aux autres de faire les choses différemment ?

Celles-ci auraient pu venir compléter la classe HTML `.center` en s'appuyant sur son fonctionnement de la façon suivante :
```css
.left {
    margin-right: auto;
}

.right {
    margin-left: auto;
}
```
Je ne suis absolument pas contre la propriété CSS `float` mais le fait que l'élément soit retiré du flux normal peut parfois être contraignant alors que ce n'est pas nécessaire.

Voici un jeu de tests mettant en évidence l'utilisation des trois classes HTML `.right`, `.center` et `.left` simultanément : http://jsfiddle.net/n56e8/1/.

Même si cela n'est pas envisageable ou souhaité pour KNACSS, je serais ravi d'avoir vos avis sur cette proposition.

Encore merci pour tout votre travail.

**Comment by raphaelgoetter** [comment]
Je suis en train de plancher sur KNACSS v4 et je me replonge dans cette problématique.

Au-delà de la rétrocompatibilité (qui n'est pas vraiment un problème tant que la branche v3 continue de vivre), voilà comment je verrais les choses : 

* `.left`, `.right` et `.center` seraient prévus pour aligner les blocs dans le flux, à l'aide de `margin`
* `.txtleft`, `.txtright` et `.txtcenter` seraient prévus pour aligner les textes et contenus, à l'aide de `text-align` (pas de changement).

Ces deux points me paraissent pertinents et cohérents. Reste le point des "flottants".

Il me serait possible d'associer les classes `.start` et `.end` aux flottants comme c'est le cas actuellement (`float: left`, `float: right`), mais quelque part je ne trouve plus ça très cohérent puisque de nouveaux types de positionnement, par exemple Flexbox, vont avoir tendance à jongler avec les notions de "start" et "end" également sans que cela ait à voir avec les flottants.

Du coup, j'ai presque envie de : 

- utiliser une classe plus "parlante" pour les flottants, comme pour les helpers de marges, par exemple `.fl` et `.fr`  (`float: left`, `float: right`)
- réserver les classes `.start` et `.end` à un autre usage... mais sans savoir encore lequel

Quelqu'un a un avis sur la question ?

**Comment by PhilippeVay** [comment]
Le temps ayant passé, je me dis que `.start` et `.end` comme clones de `.left` et `.right`, bof on en a aucune utilité. Ce sont bien les termes RTL-proof de CSS et des navigateurs mais eux ont des contraintes que l'on a pas (le RTL).
Pour ce qui est de redéfinir `.left` et `.right` : non merci. <q>Au-delà de la rétrocompatibilité (qui n'est pas vraiment un problème (…))</q> : ça me semble au contraire un écueil majeur pour des classes "qui parlent d'elles-mêmes", connues et utilisées. Je réserverais plutôt l'usage d'un préfixe aux nouveaux modes de positionnement. Sauf que f fait penser à float, fx = Firefox et fb = Facebook donc bonne chance pour en trouver un à Flexbox :p 

*Disclaimer* : j'utilise quotidiennement une version 2.6 de KNACSS (juillet 2012 en tout cas) en ayant à supporter IE8 au moins dans la résolution par défaut... Pour un utilisateur des versions récentes, tu repasseras.

**Comment by blupdew** [comment]
Personnellement je trouve les noms `.start` et `.end` peu (voire pas du tout) parlants, que ce soit pour les débutants ou les initiés qui préféreront peut-être y trouver un lien avec les termes techniques réellement utilisés derrière (propriétés CSS).

**Comment by raphaelgoetter** [comment]
Merci pour ton retour.

Mon argumentaire précédent tient surtout en 2 points : 

1- l'avenir ne passe clairement plus par le positionnement flottant, en tout cas pas massivement comme c'est le cas actuellement. Pour moi, associer .left à un flottant dans nos esprits est une faute et j'aimerais la casser avec KNACSS 4 une bonne fois pour toutes
2- KNACSS3 continuera de vivre et pourra être utilisé pour les client sous IE8. Il s'agira simplement de deux outils différents : un pour l'avenir (qu'on n'aura plus besoin de changer dans 2 ans parce qu'obsolète) et un... qui va vite devenir obsolète

**Comment by creativejuiz** [comment]
En dehors la seule problématique de rétrocompatibilité et de prise en charge du futur de CSS,il y a également la souci des classes propres à WordPress. (d'ailleurs je te dois un fichier .less à ce sujet)

WordPress, dans sa grande générosité (il a bon Core) propose : 

`.alignnone {
    margin: 5px 20px 20px 0;
}
.aligncenter,
div.aligncenter {
    display: block;
    margin: 5px auto 5px auto;
}
.alignright {
    float:right;
    margin: 5px 0 20px 20px;
}
.alignleft {
    float: left;
    margin: 5px 20px 20px 0;
}
a img.alignright {
    float: right;
    margin: 5px 0 20px 20px;
}
a img.alignnone {
    margin: 5px 20px 20px 0;
}
a img.alignleft {
    float: left;
    margin: 5px 20px 20px 0;
}
a img.aligncenter {
    display: block;
    margin-left: auto;
    margin-right: auto
}`

Le terme de align* rappelle ce bon vieil attribut HTML, et permet de libérer `.left` et `.right` si jamais tu veux les réutiliser.
Bon courage.

**Comment by raphaelgoetter** [comment]
@blupdew 

> Personnellement je trouve les noms .start et .end peu (voire pas du tout) parlants, que ce soit pour les débutants ou les initiés qui préféreront peut-être y trouver un lien avec les termes techniques réellement utilisés derrière (propriétés CSS).

Ben justement, les positionnement actuels et futurs (flexbox, grid) emploient tous des points de repères basés sur les notions de start/end plutôt que left/right (je pense notamment à align-items: flex-start), on est donc en plein dans "les termes techniques réellement utilisés"... en tout cas dans un avenir très proche :/

**Comment by raphaelgoetter** [comment]
Bon, après réflexion, je m'oriente certainement vers ce choix : 
(tl/dr : choix de l'avenir / cassage de la rétrocompatibilité)

```
/* simple blocks alignment */
.left {
	margin-right: auto;
}

.right {
	margin-left: auto;
}

.center {
	margin-left: auto;
	margin-right: auto;
}

/* text and contents alignment */
.txtleft {
	text-align: left;
}

.txtright {
	text-align: right;
}

.txtcenter {
	text-align: center;
}

/* floating elements */
.fl {
	float: left;
}

img.fl {
	margin-right: @small-value;
}

.fr {
	float: right;
}

img.fr {
	margin-left: @small-value;
}

img.fl,
img.fr {
	margin-bottom: @tiny-value;
}
```
